version: '3.8'

services:
  database:
    image: ${MYSQL_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    networks:
      - wordpress
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_vol:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    image: ${WORDPRESS_IMAGE}
    container_name: ${WP_CONTAINER_NAME}
    networks:
      - wordpress
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      - database
    restart: unless-stopped

volumes:
  db_vol:
  wp_vol:

networks:
  wordpress:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
          gateway: 172.20.0.1
